package com.tunahankara.reflex7.engine

import com.tunahankara.reflex7.R

object TaskRegistry {
    private val allGrid = Modifier.entries.toSet()

    val tasks: List<TaskDefinition> = listOf(
        TaskDefinition("standard", TaskCategory.REACTION, 1, 7.0, 1, 1.0, R.string.task_standard_name),
        TaskDefinition("package", TaskCategory.DECEPTION, 4, 3.0, 3, 1.3, R.string.task_package_name),
        TaskDefinition("hold", TaskCategory.TIMING, 3, 3.0, 2, 1.2, R.string.task_hold_name),
        TaskDefinition("colorShift", TaskCategory.REACTION, 3, 3.0, 2, 1.2, R.string.task_color_shift_name),
        TaskDefinition("wait", TaskCategory.INHIBITION, 5, 3.5, 2, 1.2, R.string.task_wait_name,
            emptySet(), setOf(Modifier.MIRRORED, Modifier.MOVING, Modifier.SHRINKING, Modifier.DECOY)),
        TaskDefinition("lastSecondInstruction", TaskCategory.INHIBITION, 7, 3.0, 3, 1.5, R.string.task_last_second_name,
            setOf(GlobalRule.FINAL_LINE), allGrid - Modifier.DELAYED, instructionPhases = InstructionPhases.MULTI_PHASE),
        TaskDefinition("patienceCountdown", TaskCategory.TIMING, 9, 3.0, 3, 1.5, R.string.task_patience_name,
            emptySet(), setOf(Modifier.MIRRORED, Modifier.MOVING, Modifier.SHRINKING, Modifier.DECOY)),
        TaskDefinition("sequence", TaskCategory.SEQUENCE, 4, 3.0, 2, 1.2, R.string.task_sequence_name),
        TaskDefinition("evade", TaskCategory.PRECISION, 6, 2.5, 3, 1.4, R.string.task_evade_name),
        TaskDefinition("oddOneOut", TaskCategory.VISUAL, 2, 4.0, 2, 1.2, R.string.task_odd_name,
            setOf(GlobalRule.IGNORE_RED, GlobalRule.ODD_WAIT), allGrid),
        TaskDefinition("numberExtremum", TaskCategory.ARITHMETIC, 3, 4.0, 2, 1.2, R.string.task_extreme_name,
            setOf(GlobalRule.IGNORE_RED, GlobalRule.ODD_WAIT), allGrid),
        TaskDefinition("parity", TaskCategory.ARITHMETIC, 5, 4.0, 2, 1.2, R.string.task_parity_name,
            setOf(GlobalRule.IGNORE_RED, GlobalRule.ODD_WAIT), allGrid),
        TaskDefinition("stroop", TaskCategory.VISUAL, 7, 3.5, 3, 1.4, R.string.task_stroop_name,
            setOf(GlobalRule.ODD_WAIT),
            setOf(Modifier.MIRRORED, Modifier.DELAYED, Modifier.DECOY, Modifier.SWAP)),
        TaskDefinition("previousMemory", TaskCategory.MEMORY, 8, 3.0, 3, 1.2, R.string.task_previous_name,
            setOf(GlobalRule.IGNORE_RED),
            setOf(Modifier.MIRRORED, Modifier.MOVING, Modifier.SHRINKING, Modifier.DECOY, Modifier.SWAP), TaskPrerequisite.PREVIOUS_NUMERIC_ANSWER),
        TaskDefinition("flashMemory", TaskCategory.MEMORY, 9, 3.0, 4, 1.6, R.string.task_flash_name,
            setOf(GlobalRule.FINAL_LINE, GlobalRule.EMOJI_LITERAL), setOf(Modifier.MIRRORED, Modifier.SHRINKING, Modifier.DECOY), instructionPhases = InstructionPhases.MULTI_PHASE),
        TaskDefinition("alphabetical", TaskCategory.LANGUAGE, 6, 3.5, 3, 1.3, R.string.task_alphabet_name,
            setOf(GlobalRule.IGNORE_RED, GlobalRule.ODD_WAIT), allGrid),
        TaskDefinition("clickPattern", TaskCategory.DECEPTION, 8, 3.0, 3, 1.1, R.string.task_click_pattern_name),
        TaskDefinition("fakeButton", TaskCategory.DECEPTION, 7, 3.0, 3, 1.2, R.string.task_fake_button_name,
            setOf(GlobalRule.IGNORE_RED, GlobalRule.ODD_WAIT), allGrid),
        TaskDefinition("delayedInstruction", TaskCategory.INHIBITION, 10, 3.0, 3, 1.5, R.string.task_delayed_name,
            setOf(GlobalRule.FINAL_LINE), setOf(Modifier.MIRRORED, Modifier.SHRINKING, Modifier.DECOY), instructionPhases = InstructionPhases.MULTI_PHASE),
        TaskDefinition("positionMemory", TaskCategory.MEMORY, 11, 3.0, 4, 1.5, R.string.task_position_name,
            setOf(GlobalRule.FINAL_LINE), setOf(Modifier.MIRRORED, Modifier.DECOY), instructionPhases = InstructionPhases.MULTI_PHASE),
        TaskDefinition("countSymbols", TaskCategory.VISUAL, 5, 4.0, 2, 1.3, R.string.task_count_name,
            setOf(GlobalRule.IGNORE_RED, GlobalRule.ODD_WAIT, GlobalRule.EMOJI_LITERAL), allGrid),
        TaskDefinition("yesNo", TaskCategory.LANGUAGE, 8, 3.0, 3, 1.2, R.string.task_yes_no_name,
            setOf(GlobalRule.INVERT, GlobalRule.IGNORE_RED, GlobalRule.ODD_WAIT), allGrid),
        TaskDefinition("directionConflict", TaskCategory.INHIBITION, 11, 3.4, 3, 1.4, R.string.task_direction_name,
            setOf(GlobalRule.INVERT, GlobalRule.ODD_WAIT), setOf(Modifier.DELAYED, Modifier.SHRINKING, Modifier.DECOY, Modifier.SWAP)),
        TaskDefinition("mentalMath", TaskCategory.ARITHMETIC, 12, 3.6, 3, 1.3, R.string.task_mental_math_name,
            setOf(GlobalRule.INVERT, GlobalRule.IGNORE_RED, GlobalRule.ODD_WAIT), allGrid),
        TaskDefinition("missingItem", TaskCategory.MEMORY, 13, 3.2, 4, 1.6, R.string.task_missing_name,
            setOf(GlobalRule.FINAL_LINE), setOf(Modifier.MIRRORED, Modifier.SHRINKING, Modifier.DECOY), instructionPhases = InstructionPhases.MULTI_PHASE),
        TaskDefinition("reverseSequence", TaskCategory.SEQUENCE, 16, 3.2, 4, 1.6, R.string.task_reverse_name,
            setOf(GlobalRule.FINAL_LINE), setOf(Modifier.MIRRORED, Modifier.SHRINKING, Modifier.DECOY), instructionPhases = InstructionPhases.MULTI_PHASE),
        TaskDefinition("countByRule", TaskCategory.VISUAL, 17, 3.5, 4, 1.5, R.string.task_count_rule_name,
            setOf(GlobalRule.IGNORE_RED, GlobalRule.ODD_WAIT), allGrid),
        TaskDefinition("oppositePosition", TaskCategory.MEMORY, 18, 3.1, 4, 1.6, R.string.task_opposite_name,
            setOf(GlobalRule.FINAL_LINE), setOf(Modifier.SHRINKING, Modifier.DECOY), instructionPhases = InstructionPhases.MULTI_PHASE),
        TaskDefinition("changingAnswer", TaskCategory.DECEPTION, 19, 3.2, 4, 1.6, R.string.task_changing_name,
            setOf(GlobalRule.FINAL_LINE), setOf(Modifier.MIRRORED, Modifier.SHRINKING, Modifier.DECOY), instructionPhases = InstructionPhases.MULTI_PHASE),
        TaskDefinition("doubleCondition", TaskCategory.INHIBITION, 21, 3.4, 5, 1.5, R.string.task_double_condition_name,
            setOf(GlobalRule.ODD_WAIT), allGrid),
        TaskDefinition("ruleSwitch", TaskCategory.INHIBITION, 23, 3.1, 5, 1.6, R.string.task_rule_switch_name,
            setOf(GlobalRule.FINAL_LINE), setOf(Modifier.MIRRORED, Modifier.SHRINKING, Modifier.DECOY), instructionPhases = InstructionPhases.MULTI_PHASE),
        TaskDefinition("nBack", TaskCategory.MEMORY, 25, 3.0, 5, 1.4, R.string.task_n_back_name,
            setOf(GlobalRule.INVERT, GlobalRule.IGNORE_RED, GlobalRule.ODD_WAIT), setOf(Modifier.MIRRORED, Modifier.SHRINKING, Modifier.DECOY, Modifier.SWAP), TaskPrerequisite.N_BACK_HISTORY),
        TaskDefinition("previousRuleRecall", TaskCategory.MEMORY, 26, 2.8, 5, 1.4, R.string.task_previous_rule_name,
            setOf(GlobalRule.ODD_WAIT), setOf(Modifier.MIRRORED, Modifier.SHRINKING, Modifier.DECOY, Modifier.SWAP), TaskPrerequisite.PREVIOUS_METADATA),
        TaskDefinition("delayedRecall", TaskCategory.MEMORY, 26, 2.7, 5, 1.5, R.string.task_delayed_recall_name,
            setOf(GlobalRule.EMOJI_LITERAL),
            setOf(Modifier.MIRRORED, Modifier.SHRINKING, Modifier.DECOY), TaskPrerequisite.DELAYED_RECALL)
    )

    fun byId(id: String): TaskDefinition = requireNotNull(tasks.find { it.id == id })
}
